AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    LakeFreezeApi:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: lake-freeze-api
            Runtime: python3.9
            CodeUri: LakeFreezeApi/
            Handler: main.handler
            
            Timeout: 300
            MemorySize: 128
            Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lake-freeze-lambda-role
                
            Events:
                Root:
                  Type: Api
                  Properties:
                    Path: /
                    Method: ANY
                Api:
                  Type: Api
                  Properties:
                    Path: /{proxy+}
                    Method: ANY
            
            VpcConfig:
                SecurityGroupIds:
                  - sg-e0fa90d6
                SubnetIds:
                  - subnet-c9fca384
                  - subnet-3266ee6d
                  - subnet-29b33c4f