AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
    DomainName:
        Type: String
        Default: kevin-mcquate.net
        
    DomainHostedZoneId:
        Type: String
        Default: Z028090523Q7W6VMX59IC

Resources:
    LakeFreezeApi:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: lake-freeze-api
            Runtime: python3.10
            CodeUri: LakeFreezeApi/
            Handler: main.handler
            
            Timeout: 300
            MemorySize: 128
            Role: !Sub arn:aws:iam::${AWS::AccountId}:role/lake-freeze-lambda-role
                
            Events:
                Root:
                  Type: Api
                  Properties:
                    Path: /
                    Method: ANY
                    # RestApiId: !Ref ApiGateway
                Api:
                  Type: Api
                  Properties:
                    Path: /{proxy+}
                    Method: ANY
                    # RestApiId: !Ref ApiGateway
            
            VpcConfig:
                SecurityGroupIds:
                  - sg-e0fa90d6
                SubnetIds:
                  - subnet-c9fca384
                  - subnet-3266ee6d
                  - subnet-29b33c4f
                  
#     TLSCertificate:
#         Type: AWS::CertificateManager::Certificate
#         Properties:
#             DomainName: !Ref DomainName
#             ValidationMethod: DNS
    
#     ApiGateway:
#         Type: AWS::Serverless::Api
#         Properties:
#             StageName: prod
#             Domain:
#               DomainName: !Ref DomainName
# #               CertificateArn: !Ref TLSCertificate
#               EndpointConfiguration: REGIONAL
#               Route53:
#                 HostedZoneId: !Ref DomainHostedZoneId
                  
  #   DBProxy:
  #     Type: AWS::RDS::DBProxy
  #     Properties:
  #         DBProxyName: rds-proxy
  #         EngineFamily: POSTGRESQL
  #         RoleArn: arn:aws:iam::117819748843:role/lake-freeze-lambda-role
  #         RequireTLS: true
  #         Auth:
  #             - {AuthScheme: SECRETS, SecretArn: arn:aws:secretsmanager:us-east-1:117819748843:secret:rds-lake-freeze-credentials-5gwihC, IAMAuth: ENABLED}
  #         VpcSubnetIds:
  #             - subnet-c9fca384
  #             - subnet-3266ee6d
  #             - subnet-29b33c4f

  # ProxyTargetGroup: 
  #     Type: AWS::RDS::DBProxyTargetGroup
  #     Properties:
  #         DbProxyName: !Ref DBProxy
  #         TargetGroupName: default
  #         InstanceIdentifiers: 
  #             - tf-20230418030022168000000001 # Name of your RDS instance
  #     DependsOn: DBProxy
