
name: Deploy SAM

on:
  push:
    branches: [ "main" ]

env:
  SAM_CLI_TELEMETRY: 0
  AWS_ACCESS_KEY_ID: "${{ secrets.AWS_ACCESS_KEY_ID }}"
  AWS_SECRET_ACCESS_KEY: "${{ secrets.AWS_SECRET_ACCESS_KEY }}"
  AWS_REGION: "${{ env.AWS_REGION }}"

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy 
    runs-on: ubuntu-latest
    environment: production
    container:
      image: public.ecr.aws/sam/build-python3.11:latest

    steps:
    - name: Checkout
      uses: taiki-e/checkout-action@v1

    - name: SAM build
      run: cd lake_freeze_api/ && sam build --debug #--use-container #--build-image public.ecr.aws/sam/build-python3.11:latest-arm64
      
    - name: SAM deploy
      run: cd lake_freeze_api/ && sam deploy --debug



